- name: Load br_netfilter module
  modprobe:
   name: br_netfilter
   state: present

- name: Update sysctl parameters - ip6tables
  sysctl:
   sysctl_file: /etc/sysctl.d/k8s.conf
   state: present
   name: net.bridge.bridge-nf-call-ip6tables
   value: 1
   reload: yes

- name: Update sysctl parameters - iptables
  sysctl:
   sysctl_file: /etc/sysctl.d/k8s.conf
   state: present
   name: net.bridge.bridge-nf-call-iptables
   value: 1
   reload: yes
