- name: Install EPEL
  yum:
   name: epel-release
   state: latest

- name: Install wget
  yum:
   name: wget
   state: latest

- name: Install screen
  yum:
   name: screen
   state: latest

- name: Install openssl
  yum:
   name: openssl
   state: latest

- name: Install pip
  yum:
   name: python-pip
   state: latest

- name: upgrade pip
  pip:
   name: pip
   state: latest
